export const productData = [
  {
    id: "PRT-1001",
    name: "Men shirt",
    category: "shirt",
    brand: "adidas",
    price: 400,
    stock: 20,
    image: "Images/f1.jpg",
    image1: "Images/f2.jpg",
    image2: "Images/f3.jpg",
    image3: "Images/f4.jpg",
    rating: 4,
    ratingCount: 1171,
    quantity: 1
  },
  {
    id: "PRT-1002",
    name: "Green leave shirt",
    category: "shirt",
    brand: "adidas",
    price: 350,
    stock: 20,
    image: "Images/f2.jpg",
    image1: "Images/f2.jpg",
    image2: "Images/f3.jpg",
    image3: "Images/f4.jpg",
    rating: 4,
    ratingCount: 1171,
    quantity: 1
  },
  {
    id: "PRT-1003",
    name: "red rose shirt",
    category: "shirt",
    brand: "adidas",
    price: 200,
    stock: 20,
    image: "Images/f3.jpg",
    image1: "Images/f2.jpg",
    image2: "Images/f3.jpg",
    image3: "Images/f4.jpg",
    rating: 4,
    ratingCount: 1171,
    quantity: 1
  },
  {
    id: "PRT-1004",
    name: " shirt",
    category: "sakura shirt",
    brand: "adidas",
    price: 200,
    stock: 20,
    image: "Images/f4.jpg",
    image1: "Images/f2.jpg",
    image2: "Images/f3.jpg",
    image3: "Images/f4.jpg",
    rating: 4,
    ratingCount: 1171,
    quantity: 1
  },
  {
    id: "PRT-1005",
    name: "pink roses shirt",
    category: "shirt",
    brand: "adidas",
    price: 200,
    stock: 20,
    image: "Images/f5.jpg",
    image1: "Images/f2.jpg",
    image2: "Images/f3.jpg",
    image3: "Images/f4.jpg",
    rating: 4,
    ratingCount: 1171,
    quantity: 1
  },
  {
    id: "PRT-1006",
    name: "New shirt",
    category: "shirt",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/f6.jpg",
    image1: "Images/f2.jpg",
    image2: "Images/f3.jpg",
    image3: "Images/f4.jpg",
    rating: 4,
    ratingCount: 1171,
    quantity: 1
  },
  {
    id: "PRT-1007",
    name: "plain white shirt",
    category: "plain shirt",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/n1.jpg",
    image1: "Images/n2.jpg",
    image2: "Images/n3.jpg",
    image3: "Images/n4.jpg",
    rating: 4,
    ratingCount: 1171,
    quantity: 1
  },
  {
    id: "PRT-1008",
    name: "gray shirt",
    category: "plain shirt",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/n2.jpg",
    image1: "Images/n2.jpg",
    image2: "Images/n3.jpg",
    image3: "Images/n4.jpg",
    rating: 4,
    ratingCount: 1171,
    quantity: 1
  },
  {
    id: "PRT-1009",
    name: "White shirt",
    category: "plain shirt",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/n3.jpg",
    image1: "Images/n2.jpg",
    image2: "Images/n3.jpg",
    image3: "Images/n4.jpg",
    rating: 4,
    ratingCount: 1542,
    quantity: 1
  },
  {
    id: "PRT-1010",
    name: "Gray leave shirt",
    category: "plain shirt",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/n4.jpg",
    image1: "Images/n2.jpg",
    image2: "Images/n3.jpg",
    image3: "Images/n4.jpg",
    rating: 4,
    ratingCount: 1124,
    quantity: 1
  },
  {
    id: "PRT-1011",
    name: "blue shirt",
    category: "plain shirt",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/n5.jpg",
    image1: "Images/n2.jpg",
    image2: "Images/n3.jpg",
    image3: "Images/n4.jpg",
    rating: 4,
    ratingCount: 1188,
    quantity: 1
  },
  {
    id: "PRT-1012",
    name: "shorts pants",
    category: "pant",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/n6.jpg",
    image1: "Images/n2.jpg",
    image2: "Images/n3.jpg",
    image3: "Images/n4.jpg",
    rating: 4,
    ratingCount: 1012,
    quantity: 1
  },
  {
    id: "PRT-1013",
    name: "brown shirt",
    category: "plain shirt",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/n7.jpg",
    image1: "Images/n2.jpg",
    image2: "Images/n3.jpg",
    image3: "Images/n4.jpg",
    rating: 4,
    ratingCount: 1071,
    quantity: 1
  },
  {
    id: "PRT-1014",
    name: "black shirt",
    category: "plain shirt",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/n8.jpg",
    image1: "Images/n2.jpg",
    image2: "Images/n3.jpg",
    image3: "Images/n4.jpg",
    rating: 4,
    ratingCount: 1179,
    quantity: 1
  },
  {
    id: "PRT-1015",
    name: "volley shirt",
    category: "shirt",
    brand: "adidas",
    price: 100,
    stock: 20,
    image: "Images/S1.jpg",
    image1: "Images/S2.jpg",
    image2: "Images/S3.jpg",
    image3: "Images/S4.jpg",
    rating: 4,
    ratingCount: 1171,
    quantity: 1
  },
  {
    id: "PRT-1016",
    name: "plain white shirt",
    category: "plain shirt",
    brand: "adidas",
    price: 50,
    stock: 20,
    image: "Images/S2.jpg",
    image1: "Images/S2.jpg",
    image2: "Images/S3.jpg",
    image3: "Images/S4.jpg",
    rating: 4,
    ratingCount: 1091,
    quantity: 1
  },
]